name: grab
channels:
  - pytorch
  - huggingface
  - conda-forge
  - defaults
dependencies:
  - numpy==2.0.1
  - pandas==2.2.3
  - flask==3.1.0
  - flask-cors==3.0.10
  - requests==2.32.3
  - pyyaml==6.0.2
  - tqdm==4.67.1
  - pymongo
  - scipy
  - matplotlib
  - python-dotenv==1.0.1
  - redis
  - accelerate
  - transformers==4.51.3
  - huggingface_hub==0.30.2
  - sentence-transformers==4.1.0
  - google-genai
  - bcrypt==4.3.0
  - PyJWT==2.10.1
  # - ortools
  - haversine